# Generated by Django 4.2 on 2025-02-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterintake',
            old_name='user',
            new_name='intake_id',
        ),
    ]
