# Generated by Django 4.2 on 2025-02-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_rename_user_waterintake_intake_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterintake',
            name='intake_id',
        ),
    ]
