# Generated by Django 4.2 on 2025-02-05 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_remove_waterintake_intake_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterintake',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
